---
name: Tests - auth
on:
  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - "auth/**.go"
      - ".github/workflows/auth-tests.yml"

env:
  AZURE_ENVIRONMENT: ${{ secrets.AZURE_ENVIRONMENT }}
  CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
  CLIENT_CERTIFICATE: ${{ secrets.AUTH_CLIENT_CERTIFICATE }}
  CLIENT_CERTIFICATE_PASSWORD: ${{ secrets.AUTH_CLIENT_CERTIFICATE_PASSWORD }}
  CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}
  MSI_TOKEN: ${{ secrets.AUTH_MSI_TOKEN }}
  TENANT_ID: ${{ secrets.TENANT_ID }}

jobs:
  test-auth:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Azure CLI login
        run: az login --allow-no-subscriptions --output none --service-principal --tenant "${TENANT_ID}" --username "${CLIENT_ID}" --password "${CLIENT_SECRET}"

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: go test -count=1 -race -v ./auth

# vim: set ts=2 sts=2 sw=2 et:
