---
name: Tests - odata
on:
  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - "odata/**.go"
      - ".github/workflows/odata-tests.yml"

jobs:
  test-odata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: go-version
        run: echo "go_version=$(cat .go-version)" >>$GITHUB_OUTPUT

      - uses: actions/setup-go@v3
        with:
          go-version: '${{ steps.go-version.outputs.go_version }}'

      - run: go test -count=1 -race -v ./odata

# vim: set ts=2 sts=2 sw=2 et:
